### ISSUE TITLE
Task list as of 05/21/24

### ISSUE THREAD

**Issue by 1628745** [ygda-org/duckin#24]
Bugs/Errors:

- As a general rule, remember to multiply speeds by delta in order to achieve consistency regardless of frame rate

- [ ] When in attack mode, if you shoot your last two ducks, the game phase ends as soon as the first one explodes, not the last one.
- [ ] $Timer.wait_time doesn't take into account frame rate, so if anybody is playing at lower than 60 FPS, they have a disadvantage during the collection stage
- [ ] Some non-physics processes are currently in _physics_process (only fixed time events should go here)
- [ ] Ducks should be collected when the player touches them, not when the player touches the seeds, because that is more visually clear, and simpler with collisions (currently the player cannot move past the duck in order to reach the seeds sometimes, preventing the collection of the duck)
- [x] The timer should appear above buildings, not below them

Major game state pieces:

- [x] When an enemy is killed, the player doesn't gain any coins
- [ ] There is no shop
- [ ] Once there is a shop, the game play loop should send you to the shop before continuing

Issues with enemies:
- [ ] Enemies should damage the player when getting too close (otherwise the optimal strategy is to wait for all enemies to be as close as possible so that you can hit them all at the same time)
- [ ] There should be a wall around the player to prevent too many enemies being in the exact same location at once (in this case, the enemies should damage the wall)
- [x] Enemies should move faster (no challenge to player)
- [ ] Enemy spawn rate should be somewhat standardized (with minor inconsistencies) because as of right now enemies can take VERY long to spawn sometimes, leaving the player with an empty screen.

Minor changes:
- [ ] Seeds should disappear after a short time as to not clutter up the screen

Art:
- [ ] Player needs graphics/animation
- [ ] UI needs an update to show coins | seeds | ducks in a visual way (and the UI should be clear even when there is a building behind it)
- [ ] Enemies need graphics and animations (with an explosion/death animation)
- [ ] If ducks "explode" then they need an explosion animation (or an attack-then-die animation if it isn't explosion)
- [ ] Background image (could even potentially steal the farmicide one as a temporary solution)
- [ ] *Maybe* a wall that the player will be situated in during the attack stage

Potential changes:
- [ ] One group of seeds should only be able to support a certain number of ducks (i.e. you can't capture 8 ducks with one seed launch)
- [ ] During the attack stage, the player shouldn't just randomly appear in another environment - we could instead "change" the time from day to night or vice-versa.  In this scenario, the shop should be a clearly designated building, and time should stop when you enter it
- [ ] Ducks shouldn't get in the way of the player.  It just ends up frustrating the game.
- [ ] The seeds shouldn't always be thrown the same distance, they should instead be based on where the player clicks, like the thrown ducks during the attack stage.
